# Generated by Django 4.2 on 2024-05-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_test_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='test_column',
        ),
    ]
